#!/usr/bin/env bash
argen &

# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
# systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

# Execute waybar at start
# kanshi &
waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css &
awww-daemon >/dev/null 2>&1 &
awww img ~/.config/hypr/assets/walls-catppuccin-mocha/car-wreck.png
zen &
